client:
    path:  /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /client
        permanent: true

readerself_core_setting:
    path:  /setting
    defaults:
        _controller: "readerself_core_controller_setting:indexAction"

readerself_core_feed:
    path:  /feed
    defaults:
        _controller: "readerself_core_controller_feed:dispatchAction"
        action: "index"
        id: null
