services:
    simplepie:
        class: SimplePie

    #Controller
    readerself_core_controller_abstract:
        class: Readerself\CoreBundle\Controller\AbstractController
        abstract: true
        calls:
            - [ "setContainer", [ "@service_container" ] ]
            - [ "setMemberManager", [ "@readerself_core_manager_member" ] ]

    readerself_core_controller_action:
        class: Readerself\CoreBundle\Controller\ActionController
        parent: "readerself_core_controller_abstract"
        arguments:
            - "@readerself_core_manager_feed"

    readerself_core_controller_feed:
        class: Readerself\CoreBundle\Controller\FeedController
        parent: "readerself_core_controller_abstract"
        arguments:
            - "@readerself_core_manager_feed"

    readerself_core_controller_subscription:
        class: Readerself\CoreBundle\Controller\SubscriptionController
        parent: "readerself_core_controller_abstract"
        arguments:
            - "@readerself_core_manager_feed"

    readerself_core_controller_item:
        class: Readerself\CoreBundle\Controller\ItemController
        parent: "readerself_core_controller_abstract"
        arguments:
            - "@readerself_core_manager_item"
            - "@readerself_core_manager_category"
            - "@readerself_core_manager_action"

    readerself_core_controller_push:
        class: Readerself\CoreBundle\Controller\PushController
        parent: "readerself_core_controller_abstract"
        arguments:
            - "@readerself_core_manager_push"

    readerself_core_controller_login:
        class: Readerself\CoreBundle\Controller\LoginController
        parent: "readerself_core_controller_abstract"

    readerself_core_controller_member:
        class: Readerself\CoreBundle\Controller\MemberController
        parent: "readerself_core_controller_abstract"

    readerself_core_controller_folder:
        class: Readerself\CoreBundle\Controller\FolderController
        parent: "readerself_core_controller_abstract"

    #Manager
    readerself_core_manager_abstract:
        class: Readerself\CoreBundle\Manager\AbstractManager
        abstract: true
        calls:
            - [ "setEntityManager", [ "@doctrine.orm.entity_manager" ] ]
            - [ "setEventDispatcher", [ "@event_dispatcher" ] ]

    readerself_core_manager_collection:
        class: Readerself\CoreBundle\Manager\CollectionManager
        parent: "readerself_core_manager_abstract"
        public: true
        arguments:
            - "@simplepie"
            - "@readerself_core_manager_push"
        calls:
            - [ "setFacebook", [ "%facebook_enabled%", "%facebook_id%", "%facebook_secret%" ] ]

    readerself_core_manager_collection_feed:
        class: Readerself\CoreBundle\Manager\CollectionFeedManager
        parent: "readerself_core_manager_abstract"
        public: true

    readerself_core_manager_feed:
        class: Readerself\CoreBundle\Manager\FeedManager
        parent: "readerself_core_manager_abstract"
        public: true
        arguments:
            - "@readerself_core_manager_collection_feed"
            - "@readerself_core_manager_subscription"

    readerself_core_manager_item:
        class: Readerself\CoreBundle\Manager\ItemManager
        parent: "readerself_core_manager_abstract"
        public: true
        arguments:
            - "@readerself_core_manager_enclosure"
            - "@readerself_core_manager_share"
        calls:
            - [ "setReadability", [ "%readability_parser_enabled%", "%readability_parser_key%" ] ]

    readerself_core_manager_enclosure:
        class: Readerself\CoreBundle\Manager\EnclosureManager
        parent: "readerself_core_manager_abstract"
        public: true

    readerself_core_manager_share:
        class: Readerself\CoreBundle\Manager\ShareManager
        parent: "readerself_core_manager_abstract"
        public: true

    readerself_core_manager_author:
        class: Readerself\CoreBundle\Manager\AuthorManager
        parent: "readerself_core_manager_abstract"
        public: true

    readerself_core_manager_category:
        class: Readerself\CoreBundle\Manager\CategoryManager
        parent: "readerself_core_manager_abstract"
        public: true
        arguments:
            - "@readerself_core_manager_item_category"

    readerself_core_manager_item_category:
        class: Readerself\CoreBundle\Manager\ItemCategoryManager
        parent: "readerself_core_manager_abstract"
        public: true

    readerself_core_manager_member:
        class: Readerself\CoreBundle\Manager\MemberManager
        parent: "readerself_core_manager_abstract"
        public: true
        arguments:
            - "@readerself_core_manager_connection"
            - "@readerself_core_manager_push"
            - "@readerself_core_manager_folder"

    readerself_core_manager_connection:
        class: Readerself\CoreBundle\Manager\ConnectionManager
        parent: "readerself_core_manager_abstract"
        public: true

    readerself_core_manager_push:
        class: Readerself\CoreBundle\Manager\PushManager
        parent: "readerself_core_manager_abstract"
        public: true
        arguments:
            - "%google_cloud_messaging_key%"

    readerself_core_manager_folder:
        class: Readerself\CoreBundle\Manager\FolderManager
        parent: "readerself_core_manager_abstract"
        public: true

    readerself_core_manager_subscription:
        class: Readerself\CoreBundle\Manager\SubscriptionManager
        parent: "readerself_core_manager_abstract"
        public: true

    readerself_core_manager_action:
        class: Readerself\CoreBundle\Manager\ActionManager
        parent: "readerself_core_manager_abstract"
        public: true
        arguments:
            - "@readerself_core_manager_action_item"
            - "@readerself_core_manager_action_item_member"
            - "@readerself_core_manager_action_category_member"

    readerself_core_manager_action_item:
        class: Readerself\CoreBundle\Manager\ActionItemManager
        parent: "readerself_core_manager_abstract"
        public: true

    readerself_core_manager_action_item_member:
        class: Readerself\CoreBundle\Manager\ActionItemMemberManager
        parent: "readerself_core_manager_abstract"
        public: true

    readerself_core_manager_action_category_member:
        class: Readerself\CoreBundle\Manager\ActionCategoryMemberManager
        parent: "readerself_core_manager_abstract"
        public: true
