Readerself\CoreBundle\Entity\Feed:
    properties:
        title:
            - Length:
                max: 255
        link:
            - NotBlank: ~
            - Length:
                max: 255
        website:
            - Length:
                max: 255
        language:
            - Length:
                min: 2
                max: 2

Readerself\CoreBundle\Entity\Member:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: email
    properties:
        email:
            - NotBlank: ~
            - Email: ~
            - Length:
                max: 255
        plainPassword:
            - NotBlank: { groups: [insert] }
            - Type: string
            - Length:
                min: 6

Readerself\CoreBundle\Entity\Login:
    properties:
        email:
            - NotBlank: ~
        password:
            - NotBlank: ~

Readerself\CoreBundle\Entity\Profile:
    properties:
        email:
            - NotBlank: ~
            - Email: ~
            - Length:
                max: 255

Readerself\CoreBundle\Entity\Pinboard:
    properties:
        token:
            - NotBlank: ~
            - Length:
                max: 255
