NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix: "/api/doc"

ReaderselfCoreBundle:
    resource: "@ReaderselfCoreBundle/Resources/config/routing.yml"
    prefix: "/api"
