Readerself\CoreBundle\Entity\Action:
    repositoryClass: Readerself\CoreBundle\Repository\ActionRepository
    type: entity
    table: action
    uniqueConstraints:
        title:
            columns:
                - title
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        dateCreated:
            type: datetime
            nullable: false
            column: date_created
    oneToOne:
        reverse:
            targetEntity: Action
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                reverse:
                    referencedColumnName: id
                    onDelete: "set null"
            orphanRemoval: false
lifecycleCallbacks: {  }
