Readerself\CoreBundle\Entity\Setting:
    type: entity
    table: setting
    indexes:
        section_id:
            columns:
                - section_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        code:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        type:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        value:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        note:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        public:
            type: boolean
            nullable: false
            options:
                default: '0'
        ordering:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
        dateCreated:
            type: datetime
            nullable: false
            column: date_created
    manyToOne:
        section:
            targetEntity: SettingSection
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                section_id:
                    referencedColumnName: id
                    onDelete: "cascade"
            orphanRemoval: false
    lifecycleCallbacks: {  }
