Readerself\CoreBundle\Entity\Subscription:
    repositoryClass: Readerself\CoreBundle\Repository\SubscriptionRepository
    type: entity
    table: subscription
    indexes:
        member_id:
            columns:
                - member_id
        feed_id:
            columns:
                - feed_id
    uniqueConstraints:
        member_id_feed_id:
            columns:
                - member_id
                - feed_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        dateCreated:
            type: datetime
            nullable: false
            column: date_created
    manyToOne:
        feed:
            targetEntity: Feed
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                feed_id:
                    nullable: false
                    referencedColumnName: id
                    onDelete: "cascade"
            orphanRemoval: false
        member:
            targetEntity: Member
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                member_id:
                    nullable: false
                    referencedColumnName: id
                    onDelete: "cascade"
            orphanRemoval: false
    lifecycleCallbacks: {  }
