#crud
readerself_api_author_create:
    path: /author
    defaults:
        _controller: "readerself_core_controller_author:createAction"
    methods: POST

readerself_api_author_read:
    path: /author/{id}
    defaults:
        _controller: "readerself_core_controller_author:readAction"
    requirements:
        id: '\d+'
    methods: GET

readerself_api_author_update:
    path: /author/{id}
    defaults:
        _controller: "readerself_core_controller_author:updateAction"
    requirements:
        id: '\d+'
    methods: PUT

readerself_api_author_delete:
    path: /author/{id}
    defaults:
        _controller: "readerself_core_controller_author:deleteAction"
    requirements:
        id: '\d+'
    methods: DELETE
