#crud
readerself_api_category_create:
    path: /category
    defaults:
        _controller: "readerself_core_controller_category:createAction"
    methods: POST

readerself_api_category_read:
    path: /category/{id}
    defaults:
        _controller: "readerself_core_controller_category:readAction"
    requirements:
        id: '\d+'
    methods: GET

readerself_api_category_update:
    path: /category/{id}
    defaults:
        _controller: "readerself_core_controller_category:updateAction"
    requirements:
        id: '\d+'
    methods: PUT

readerself_api_category_delete:
    path: /category/{id}
    defaults:
        _controller: "readerself_core_controller_category:deleteAction"
    requirements:
        id: '\d+'
    methods: DELETE

#extra
readerself_api_category_exclude:
    path: /category/exclude/{id}
    defaults:
        _controller: "readerself_core_controller_category:excludeAction"
    requirements:
        id: '\d+'
    methods: GET
