#crud
readerself_api_connection_create:
    path: /connection
    defaults:
        _controller: "readerself_core_controller_connection:createAction"
    methods: POST

readerself_api_connection_read:
    path: /connection/{id}
    defaults:
        _controller: "readerself_core_controller_connection:readAction"
    requirements:
        id: '\d+'
    methods: GET

readerself_api_connection_update:
    path: /connection/{id}
    defaults:
        _controller: "readerself_core_controller_connection:updateAction"
    requirements:
        id: '\d+'
    methods: PUT

readerself_api_connection_delete:
    path: /connection/{id}
    defaults:
        _controller: "readerself_core_controller_connection:deleteAction"
    requirements:
        id: '\d+'
    methods: DELETE
