#crud
readerself_api_item_read:
    path: /item/{id}
    defaults:
        _controller: "readerself_core_controller_item:readAction"
    requirements:
        id: '\d+'
    methods: GET

readerself_api_item_delete:
    path: /item/{id}
    defaults:
        _controller: "readerself_core_controller_item:deleteAction"
    requirements:
        id: '\d+'
    methods: DELETE

#extra
readerself_api_items:
    path: /items
    defaults:
        _controller: "readerself_core_controller_item:indexAction"
    methods: GET

readerself_api_items_markallasread:
    path: /items/markallasread
    defaults:
        _controller: "readerself_core_controller_item:markallasreadAction"
    methods: GET

readerself_api_item_action_read:
    path: /item/action/read/{id}
    defaults:
        _controller: "readerself_core_controller_item:actionReadAction"
    requirements:
        id: '\d+'
    methods: GET

readerself_api_item_action_star:
    path: /item/action/star/{id}
    defaults:
        _controller: "readerself_core_controller_item:actionStarAction"
    requirements:
        id: '\d+'
    methods: GET

readerself_api_item_action_email:
    path: /item/action/email/{id}
    defaults:
        _controller: "readerself_core_controller_item:actionEmailAction"
    requirements:
        id: '\d+'
    methods: POST

readerself_api_search_items:
    path: /items/search
    defaults:
        _controller: "readerself_core_controller_search:itemsAction"
    methods: GET

