services:
    axipi_core_controller_abstract:
        class: Axipi\FeedBundle\Controller\AbstractController
        abstract: true
        calls:
            - [ "setContainer", [ "@service_container" ] ]

    axipi_core_controller_default:
        class: Axipi\FeedBundle\Controller\DefaultController
        parent: "axipi_core_controller_abstract"

    axipi_core_manager_abstract:
        class: Axipi\FeedBundle\Manager\AbstractManager
        abstract: true
        calls:
            - [ "setEntityManager", [ "@doctrine.orm.entity_manager" ] ]
            - [ "setEventDispatcher", [ "@event_dispatcher" ] ]

    axipi_core_manager_feed:
        class: Axipi\FeedBundle\Manager\FeedManager
        parent: "axipi_core_manager_abstract"
        public: true

    simplepie:
        class: SimplePie
