Axipi\FeedBundle\Entity\Enclosure:
    type: entity
    table: enclosure
    indexes:
        item_id:
            columns:
                - item_id
        type:
            columns:
                - type
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        link:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        type:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        length:
            type: integer
            nullable: true
            options:
                unsigned: true
        width:
            type: integer
            nullable: true
            options:
                unsigned: true
        height:
            type: integer
            nullable: true
            options:
                unsigned: true
        dateCreated:
            type: datetime
            nullable: false
            column: date_created
    manyToOne:
        item:
            targetEntity: Item
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                item_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
